spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AppDatabase
    username: AppUser
    password: AppPassword
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0